### ISSUE TITLE
wcc ends in panic:timeout

### ISSUE THREAD

**Issue by jwiggers** [whitecatboard/whitecat-console#1]
LS,

I am trying to flash lua rtos with wcc to my nodemcu esp8266 and get the following results. This is from MacOs but i get exactly the same results on windows. What am i doing wrong?

Jans-Mac-mini:LUA RTOS jan$ ./wcc -p /dev/cu.SLAB_USBtoUART -f -d
2017/09/26 09:02:44 AppFolder:  /Users/jan/Documents/Projects/Embedded/LUA RTOS
2017/09/26 09:02:44 AppFileName:  /Users/jan/Documents/Projects/Embedded/LUA RTOS/wcc
2017/09/26 09:02:44 AppDataFolder:  /Users/jan/.wccagent
2017/09/26 09:02:44 AppDataTmpFolder:  /Users/jan/.wccagent/tmp
2017/09/26 09:02:44 connecting to board on /dev/cu.SLAB_USBtoUART ...
2017/09/26 09:02:44 attaching board ...
2017/09/26 09:02:44 start inspector ...
2017/09/26 09:02:44 waiting for ready ...
2017/09/26 09:02:48 board attached
2017/09/26 09:02:50 detaching board ...
2017/09/26 09:02:50 closing serial port ...
2017/09/26 09:02:50 stop inspector ...
panic: timeout

goroutine 1 [running]:
main.(*Board).read(0xc42006a070, 0xc420110000)
	/Users/jolive/gows/src/github.com/whitecatboard/whitecat-console/board.go:306 +0x16d
main.(*Board).readLineCRLF(0xc42006a070, 0xc4200140a0, 0xc)
	/Users/jolive/gows/src/github.com/whitecatboard/whitecat-console/board.go:320 +0x49
main.(*Board).sendCommand(0xc42006a070, 0x42e1990, 0xa, 0xc420071190, 0xc420076d50)
	/Users/jolive/gows/src/github.com/whitecatboard/whitecat-console/board.go:441 +0xd0
main.main()
	/Users/jolive/gows/src/github.com/whitecatboard/whitecat-console/main.go:253 +0x1f6c
Jans-Mac-mini:LUA RTOS jan$

**Comment by the0ne** [comment]
Hi @jwiggers you need to replace SLAB_USBtoUART by your actual USB enumeration name.

You may use the -ports parameter to wcc:
`./wcc -ports`
as this will show you a list of available usb devices.

Other users of MacOS seem to have names like the following, just as an example:
`./wcc -p /dev/cu.usbserial-FTYKHBJT -f -ffs -d`
