### ISSUE TITLE
Exception while running

### ISSUE THREAD

**Issue by fcasarsa** [whitecatboard/whitecat-console#3]
On windows 10 running wcc as administrator from c:\windows\system32 throws this error:

`Microsoft Windows [Versione 10.0.16299.192]
(c) 2017 Microsoft Corporation. Tutti i diritti sono riservati.

C:\WINDOWS\system32>wcc
usage: wcc -p port | -ports [-ls path | [-down source destination] | [-up source destination] | [-f | -ffs] | [-erase] | -d]

-ports:          list all available serial ports on your computer
-p port:         serial port, for example COM2
-ls path:        list files present in path
-down src dst:   transfer the source file (board) to destination file (computer)
-up src dst:     transfer the source file (computer) to destination file (board)
-f:              flash board with last firmware
-ffs:            flash board with last filesystem
-erase:          erase flash board
-d:              show debug messages

C:\WINDOWS\system32>wcc -ports
Available serial ports on your computer:

Exception 0xc0000005 0x0 0x6ab8 0x7f79f5
PC=0x7f79f5
signal arrived during external code execution

github.com/whitecat-console/vendor/github.com/mikepb/go-serial._Cfunc_sp_list_ports(0xc042004038, 0xc000000000)
        github.com/whitecat-console/vendor/github.com/mikepb/go-serial/_obj/_cgo_gotypes.go:560 +0x50
github.com/whitecat-console/vendor/github.com/mikepb/go-serial.ListPorts.func1(0xc042004038, 0xc042004038)
        d:/gows/src/github.com/whitecat-console/vendor/github.com/mikepb/go-serial/serial.go:328 +0xc4
github.com/whitecat-console/vendor/github.com/mikepb/go-serial.ListPorts(0x0, 0x0, 0x0, 0x0, 0x0)
        d:/gows/src/github.com/whitecat-console/vendor/github.com/mikepb/go-serial/serial.go:328 +0x8e
main.list_ports()
        d:/gows/src/github.com/whitecat-console/connection.go:85 +0x2d
main.main()
        d:/gows/src/github.com/whitecat-console/main.go:186 +0x22c6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:2197 +0x1
rax     0x1
rbx     0x258
rcx     0x9e772801f4520000
rdi     0x7ff9337761a0
rsi     0x1
rbp     0x6a70
rsp     0xa8f500
r8      0x7
r9      0x200
r10     0x7ff933b00000
r11     0x0
r12     0xa8f590
r13     0xa8f8f0
r14     0xa8f578
r15     0x3366d40
rip     0x7f79f5
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

C:\WINDOWS\system32>wcc -p COM2 -f -ffs
Exception 0xc0000005 0x0 0x6d18 0x7f79f5
PC=0x7f79f5
signal arrived during external code execution

github.com/whitecat-console/vendor/github.com/mikepb/go-serial._Cfunc_sp_get_port_by_name(0x32417a0, 0xc042004038, 0xc000000000)
        github.com/whitecat-console/vendor/github.com/mikepb/go-serial/_obj/_cgo_gotypes.go:425 +0x54
github.com/whitecat-console/vendor/github.com/mikepb/go-serial.portByName.func2(0x32417a0, 0xc042004038, 0x32417a0)
        d:/gows/src/github.com/whitecat-console/vendor/github.com/mikepb/go-serial/serial.go:317 +0xce
github.com/whitecat-console/vendor/github.com/mikepb/go-serial.portByName(0xc04200c220, 0x4, 0x0, 0x0, 0x0)
        d:/gows/src/github.com/whitecat-console/vendor/github.com/mikepb/go-serial/serial.go:317 +0xc3
github.com/whitecat-console/vendor/github.com/mikepb/go-serial.PortByName(0xc04200c220, 0x4, 0xc042071680, 0xc0420c81a0, 0xc04205d680)
        d:/gows/src/github.com/whitecat-console/vendor/github.com/mikepb/go-serial/serial.go:305 +0x40
main.connect(0xc04206de01, 0xc04200c220, 0x4)
        d:/gows/src/github.com/whitecat-console/connection.go:60 +0x1b8
main.main()
        d:/gows/src/github.com/whitecat-console/main.go:258 +0xea4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        D:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive]:
main.console()
        d:/gows/src/github.com/whitecat-console/connection.go:48 +0x49
created by main.connect
        d:/gows/src/github.com/whitecat-console/connection.go:57 +0x19a
rax     0x1
rbx     0x2d8
rcx     0xe4aa29a174ad0000
rdi     0x7ff9337761a0
rsi     0x1
rbp     0x6cd0
rsp     0xa8f690
r8      0x7
r9      0x200
r10     0x7ff933b00000
r11     0x0
r12     0xa8f720
r13     0xa8fa80
r14     0xa8f708
r15     0x3246ea0
rip     0x7f79f5
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

C:\WINDOWS\system32>`

Hints or suggestions are welcome! 

Thanks.

**Comment by Bazmundi** [comment]
#fcasarsa

I am struggling through my first steps too.

I got exception 0xc0000005 0x0 0x810f 0x7ffeac98ecf4

But I had my wcc saved to D: drive, away from needing the admin rights in system32.

Given the span of time since you asked the question, and their being no response, I would guess this software is not supported very well.

I downloaded the binaries and am now trying to build them instead, to see if that makes a difference.

**Comment by Bazmundi** [comment]
#fcasarsa
No good, I get a stream of errors when I use the following:

`go get github.com/whitecatboard/whitecat-console`

And that is either with standard windoze console or the admin console.

Pity, it seemed a good thing.
